[package]
name = 'movement_names_distribute'
version = '1.0.0'

[dependencies.movement_names]
local = "../core"

[dependencies.AptosToken]
git = 'https://github.com/aptos-labs/aptos-core.git'
rev = 'mainnet'
subdir = 'aptos-move/framework/aptos-token'
